app_sec/auth.py
import base64
from io import BytesIO
from flask import Blueprint, app, jsonify, render_template, request, redirect, url_for, session
from flask import current_app, session, request, jsonify
import qrcode
from .database import *
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import secure_filename
import re
from email_validator import validate_email, EmailNotValidError
import hashlib
import requests
import pyotp
import time
import os

auth = Blueprint('auth', __name__)

class User:
    def __init__(self, username, email, password):
        self.username = username
        self.email = email
        self.password = generate_password_hash(password)  

UPLOAD_FOLDER = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'static/images/uploads')
ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg', 'gif'}

if not os.path.exists(UPLOAD_FOLDER):
    os.makedirs(UPLOAD_FOLDER)
    
def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

        
def check_breached_password(password):
    sha1_password = hashlib.sha1(password.encode('utf-8')).hexdigest().upper()
    prefix, suffix = sha1_password[:5], sha1_password[5:]
    url = f"https://api.pwnedpasswords.com/range/{prefix}"
    
    response = requests.get(url)
    if response.status_code != 200:
        raise RuntimeError("Error fetching breached passwords")

    hash_suffixes = (line.split(':') for line in response.text.splitlines())
    for hsuffix, count in hash_suffixes:
        if suffix == hsuffix:
            return True
    return False

@auth.route('/login', methods=['POST', 'GET'])
def login():
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']
        totp_code = request.form['totp'].strip()
        errors = {}
        
        can_attempt, error_message = check_login_attempts(email)
        if not can_attempt:
            errors["attempts"] = error_message
            return render_template('login.html', email=email, errors=errors)

        user_password = get_user_password(email)

        if user_password and check_password_hash(user_password, password):
            user_totp_secret = get_user_totp_secret(email)
            
            totp = pyotp.TOTP(user_totp_secret)

            is_totp_valid = totp.verify(totp_code, valid_window=3)
            
            if check_breached_password(password):
                errors["breached"] = "This password has been compromised in a data breach. Please choose a different password."
                return render_template('login.html', email=email, errors=errors)

            if is_totp_valid:
                session.permanent = True
                session.clear()
                session['user'] = {'email': email, 'username': get_username(email)}
                clear_login_attempts(email)

                return redirect(url_for('views.home'))
            else:
                errors["incorrect_totp"] = "Invalid TOTP code."
                increment_login_attempts(email)
                return render_template('login.html', email=email, errors=errors)
        else:
            errors["incorrect_password"] = "Invalid email or password."
            increment_login_attempts(email)
            return render_template('login.html', email=email, errors=errors)
    return render_template('login.html')



@auth.route('/sign-up', methods=['POST', 'GET'])
def sign_up():
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password1']
        password_confirm = request.form['password2']
        username = request.form['username']
        errors = {}
        
        if email_exists(email):
            errors["email"] = "Email already exists. Please choose a different email."

        if username_exists(username):
            errors["username"] = "Username already exists. Please choose a different username."

        password = re.sub(r'\s+', ' ', password).strip()
        password_confirm = re.sub(r'\s+', ' ', password_confirm).strip()


        if check_breached_password(password):
            errors["breached"] = "This password has been compromised in a data breach. Please choose a different password."

        try:
            valid = validate_email(email)
            email = valid.email
        except EmailNotValidError as e:
            errors["email"] = str(e)

        if len(password) < 12 or len(password) > 128:
            errors["length"] = "Password must be at least 12 characters long and less than 128 characters."
        if password != password_confirm:
            errors["confirm"] = "Passwords do not match."

        if not errors:
            if not verify_user(email):

                totp_secret = pyotp.random_base32()
                
                add_user(email, generate_password_hash(password), username, totp_secret)

                totp_uri = pyotp.totp.TOTP(totp_secret).provisioning_uri(name=email, issuer_name="eDeti shop")
                qr = qrcode.make(totp_uri)
                img_io = BytesIO()
                qr.save(img_io, 'PNG')
                img_io.seek(0)
                qr_data = img_io.getvalue()
                qr_b64 = base64.b64encode(qr_data).decode('ascii')
                qr_image = f"data:image/png;base64,{qr_b64}"

                return render_template('sign_up.html', totp_uri=totp_uri, totp_qr_image=qr_image)

            else:
                return render_template('sign_up.html', email_in_use=True, email=email, username=username)
        
        return render_template('sign_up.html', errors=errors, email=email, username=username)
    
    return render_template('sign_up.html')

@auth.route('/logout')
def logout():
    session.clear()  
    return redirect(url_for('auth.login'))


@auth.route('/change_avatar', methods=['POST'])
def change_avatar():
    email = session['user']['email']
    if 'user' not in session:
        return redirect(url_for('auth.login'))
    errors = {}
    MAX_FILE_SIZE = 5*1024*1024

    if 'avatar' in request.files:
        file = request.files['avatar']
        if file and allowed_file(file.filename):
            file.seek(0, os.SEEK_END)
            if file.tell() > MAX_FILE_SIZE:
                errors["avatar"] = "File size exceeds 5MB."
                return render_template('profile.html', email=session['user']['email'], username=session['user']['username'], avatar=session['user'].get('avatar'), errors=errors)
            
            file.seek(0)
            filename = secure_filename(file.filename)
            file.save(os.path.join(current_app.root_path, 'static/uploads', filename))

            update_avatar(email, filename)

            session['user']['avatar'] = filename
            errors["avatar"] = "Avatar updated successfully."
        else:
            errors["avatar"] = "Invalid file type. Please upload a valid image file."

    if errors:
        return render_template('profile.html', email=session['user']['email'], username=session['user']['username'], avatar=session['user'].get('avatar'), errors=errors)

    return render_template('profile.html', email=session['user']['email'], username=session['user']['username'], avatar=session['user'].get('avatar'))



@auth.route('/profile', methods=['GET', 'POST'])
def profile():
    if 'user' not in session:
        return redirect(url_for('auth.login'))
    if request.method == 'POST':
        email = session['user']['email']
        errors = {}

        # Handle password change
        old_password = request.form.get('old-password')
        new_password = request.form.get('new-password')
        new_password_confirm = request.form.get('confirm-password')

        new_password = re.sub(r'\s+', ' ', new_password).strip()
        new_password_confirm = re.sub(r'\s+', ' ', new_password_confirm).strip()

        if not check_password_hash(get_user_password(email), old_password):
            errors['old-password'] = 'Incorrect password.'

        if check_breached_password(new_password):
            errors['breached'] = "This password has been compromised in a data breach. Please choose a different password."

        if new_password != new_password_confirm:
            errors['new-password'] = 'Passwords do not match.'
        if len(new_password) < 12 or len(new_password) > 128:
            errors['length'] = 'Password must be at least 12 characters long and less than 128 characters.'

        if errors:
            return jsonify(errors=errors), 400

        new_hashed_password = generate_password_hash(new_password)
        update_password(email, new_hashed_password)
        return render_template('profile.html', email=session['user']['email'], username=session['user']['username'], avatar=session['user'].get('avatar'), password_updated=True)

    return render_template('profile.html', email=session['user']['email'], username=session['user']['username'], avatar=session['user'].get('avatar'))

@auth.route('/delete_account', methods=['POST'])
def delete_account():
    if 'user' not in session:
        return redirect(url_for('auth.login'))
    
    email = session['user']['email']
    
    delete_user_account(email)
    
    session.clear()
    return redirect(url_for('auth.login'))

app_sec/templates/about.html
{% extends "base.html" %}
{% block title %}eDeti Shop{% endblock %}
{% block head %}
<link rel="stylesheet" href="{{url_for('static', filename='css/about.css')}}">
{% endblock %}
<div class="d-flex flex-column" style="min-height: 990px;"></div>
{% block body %}

<section class="about">
  <div class="about-section">
      <h1>About Us Page</h1>
      <p>This is the about us page of the project of Segurança Informática e nas Organizações</p>
      <p>This project was done by:</p>
      <p>Francisco Gonçalves Nmec: 1085381</p>
    </div>  
    
  <div class="about-description">
    <h3>Project description</h3>
    <p>The assignment focuses on vulnerabilities in software projects, their exploration, and prevention. 
      We were required to develop a small online shop application selling memorabilia for the Department of Electronics, 
      Telecommunications, and Informatics (DETI) at the University of Aveiro. The online shop features items like mugs, cups, 
      t-shirts, hoodies, and similar memorabilia.</p>
      <p>In this project we implemented some CWE that were requested such as:</p>
      <p>CWE-79 (Cross-Site Scripting) <br>CWE-89 (SQL Injection)</p>
      <p>We also implemented others vulnerabilities:</p>      
      <p>Cwe-20: Improper Input Validation</p>
      <p>CWE-22 Improper Limitation of a Pathname to a Restricted Directory ('Path Traversal')</p>
      <p>CWE-521: Weak Password Requirements</p>      
      <p>CWE-522 - Insufficiently Protected Credentials</p>
      <p>CWE-601: URL Redirection to Untrusted Site ('Open Redirect')</p>
      <p>CWE-798 Use of Hard-coded Credentials</p>
  </div>
</section>

{% endblock %}

app_sec/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{url_for('static', filename='css/bootstrap.css')}}">
    <!-- Font Awesome -->
    <link
    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
    rel="stylesheet"
    />
    <link href="https://fonts.cdnfonts.com/css/amazon-ember" rel="stylesheet">
    <style>
      @import url('https://fonts.cdnfonts.com/css/amazon-ember');
    </style>
    <!-- Handle JQuery -->
    <script type="text/javascript" src="https://code.jquery.com/jquery-1.7.1.min.js"></script>
    <!-- Google Fonts -->
    <!-- <link
    href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
    rel="stylesheet"
    /> -->
    <style>
      @import url('https://fonts.googleapis.com/css2?family=Open+Sans:wght@500&display=swap');
    </style>
    <!-- Inter font -->
    <link href='https://fonts.googleapis.com/css?family=Inter' rel='stylesheet'>
    <!-- Bootstrap 5 -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">    {% block head %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>
    <!-- Custom CSS -->
    <link rel="stylesheet" href=" {{ url_for('static', filename='css/base.css') }}">
    <link rel="stylesheet" href=" {{ url_for('static', filename='css/style.css') }}">
</head>
  {% block beforenav %}{% endblock %}
    <header>
      <div class="navbar">
          <div class="logo"><a href="/">eDeti shop</a></div>
          <ul class="links">
              <li><a href="/">Home</a></li>
              <li><a href="/about">About Us</a></li>
          </ul>
          <div class="col-r">
            <a href="/cart" class="shop-cart"><i class="fa-solid fa-shopping-cart"></i></a>
            <a href="/profile" class="shop-cart"><i class="fa-solid fa-user"></i></a>
          </div>
          <div class="toggle_btn">
              <i class="fa-solid fa-bars"></i>
          </div>

          <div class="dropdown_menu">
              <li><a href="/">Home</a></li>
              <li><a href="/about">About Us</a></li>
              <li><a href="/products" class="action_btn">Shop Now</a></li>
              <li><a href="/cart" class="shop-cart"><i class="fa-solid fa-shopping-cart"></i></a></li>
          </div>
      </div>

      <script>
          const toggleBtn = document.querySelector('.toggle_btn')
          const toggleBtnIcon = document.querySelector('.toggle_btn i')
          const dropDownMenu = document.querySelector('.dropdown_menu')

          toggleBtn.onclick = function () {
              dropDownMenu.classList.toggle('open')
          }
      </script>
  </header>
  {% block body %}
  {% endblock %}


  <footer class="footer">
    <div class="container">
      <p>© 2023 DETI, Universidade de Aveiro</p>
    </div>
  </footer>
</html>

app_sec/templates/cart.html
{% extends "base.html" %}
{% block title %}eDeti Shop{% endblock %}
{% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/cart.css') }}">
{% endblock %}
{% block body %}
<div class="container mt-5">
    <div class="cart-container">
        <h1 class="mb-4">Your Shopping Cart</h1>
        <table class="table">
            <thead>
                <tr>
                    <th>Item Name</th>
                    <th>Quantity</th>
                    <th>Price</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% for item in cart %}
                <tr>
                    <td>{{ item[3]  }}</td>  <!-- Escapes output to prevent XSS -->
                    <td>{{ item[1]  }}</td>
                    <td>{{ item[2]  }}</td>
                    <td>
                        <form method="POST" action="{{ url_for('views.remove_item') }}">
                            <input type="hidden" name="csrf_token" value="{{csrf_token()}}">
                            <button class="btn btn-danger action-button" type="submit">Remove</button>
                            <input type="hidden" name="product_id" value="{{ item[0] | e }}">  <!-- Escape to prevent potential XSS -->
                        </form>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <div class="total-price">
            <h4>Total Price: ${{ total_price }}</h4>  <!-- Display the total price -->
        </div>
        <a class="action_btn" href="/checkout">Checkout</a>
    </div>
</div>
{% endblock %}

app_sec/templates/checkout.html
{% extends "base.html" %}
{% block title %}eDeti Shop - Checkout{% endblock %}
{% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/checkout.css') }}">
{% endblock %}
{% block body %}
<section class="c-wrapper">
    <div class="c-left">
        <h1>Checkout</h1>
        <div class="shadow-line"></div>

        <!-- Display errors if any -->
        {% if errors %}
        <div class="error-container">
            <ul>
                {% for error in errors.values() %}
                <li class="error">{{ error }}</li>
                {% endfor %}
            </ul>
        </div>
        {% endif %}

        <div class="l-box">
            <h2>Your basic information</h2>
            <ul class="l-inputs">
                <li>
                    <label for="fname">First name*</label><br>
                    <input type="text" id="fname" name="fname" value="{{ request.form.get('fname', '') }}"><br>
                </li>
                <li>
                    <label for="lname">Last name*</label><br>
                    <input type="text" id="lname" name="lname" value="{{ request.form.get('lname', '') }}"><br>
                </li>
                <li>
                    <label for="email">Email*</label><br>
                    <input type="email" id="email" name="email" value="{{ request.form.get('email', '') }}">
                </li>
            </ul>
        </div>
        <div class="shadow-line"></div>
        <div class="l-box">
            <h2>Your Payment Information</h2>
            <!-- Payment -->
            <ul class="l-pay">
                <li>
                    <label for="ccard">Credit Card*</label><br>
                    <input type="text" id="ccard" name="ccard" placeholder="XXXX XXXX XXXX XXXX"
                        value="{{ request.form.get('ccard', '') }}"><br>
                </li>
                <li>
                    <label for="exp">Expiry date*</label><br>
                    <input type="month" id="exp" name="exp" placeholder="mm/yy"
                        value="{{ request.form.get('exp', '') }}"><br>
                </li>
                <li>
                    <label for="cvcv">CVC/CVV*</label><br>
                    <input type="number" id="cvcv" name="cvcv" placeholder="XXX"
                        value="{{ request.form.get('cvcv', '') }}">
                </li>
            </ul>
            <form method="POST" action="{{ url_for('views.pay') }}" onsubmit="return validateForm()">
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                <div class="l-box">
                    <h2>Re-enter your password to proceed</h2>
                    <ul class="l-inputs">
                        <li>
                            <label for="password">Password*</label><br>
                            <input type="password" id="password" name="password" placeholder="Enter your password"><br>
                        </li>
                    </ul>
                    <!-- Insert the following block before the "Proceed" button in the Checkout page -->
                    <div class="form-check mb-4">
                        <input type="checkbox" class="form-check-input" id="privacyConsentCheckout" required>
                        <label class="form-check-label" for="privacyConsentCheckout">
                            I agree to the <a href="/privacy-policy" target="_blank">Privacy Policy</a> and consent to
                            the collection and use of my personal information as described therein.
                        </label>
                    </div>
                </div>
                <button class="action_btn">Proceed</button>
            </form>
        </div>
    </div>
    <script>
        function validateForm() {
            let isValid = true;
            let errorMessages = [];
    
            // Get all the input fields
            const fname = document.getElementById('fname').value.trim();
            const lname = document.getElementById('lname').value.trim();
            const email = document.getElementById('email').value.trim();
            const ccard = document.getElementById('ccard').value.trim();
            const exp = document.getElementById('exp').value.trim();
            const cvcv = document.getElementById('cvcv').value.trim();
            const password = document.getElementById('password').value.trim();
            const privacyConsent = document.getElementById('privacyConsentCheckout').checked;
    
            // Validate each field
            if (!fname) {
                errorMessages.push("First name is required.");
                isValid = false;
            }
            if (!lname) {
                errorMessages.push("Last name is required.");
                isValid = false;
            }
            if (!email) {
                errorMessages.push("Email is required.");
                isValid = false;
            } else if (!validateEmail(email)) {
                errorMessages.push("Please enter a valid email address.");
                isValid = false;
            }
            if (!ccard) {
                errorMessages.push("Credit card number is required.");
                isValid = false;
            } else if (!validateCreditCard(ccard)) {
                errorMessages.push("Please enter a valid credit card number.");
                isValid = false;
            }
            if (!exp) {
                errorMessages.push("Expiry date is required.");
                isValid = false;
            }
            if (!cvcv) {
                errorMessages.push("CVC/CVV is required.");
                isValid = false;
            }
            if (!password) {
                errorMessages.push("Password is required.");
                isValid = false;
            }
            if (!privacyConsent) {
                errorMessages.push("You must agree to the Privacy Policy.");
                isValid = false;
            }
    
            // Display error messages
            if (!isValid) {
                alert(errorMessages.join("\n"));
            }
    
            return isValid;
        }
    
        function validateEmail(email) {
            const re = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
            return re.test(String(email).toLowerCase());
        }
    
        function validateCreditCard(ccard) {
            const re = /^\d{4}\d{4}\d{4}\d{4}$/;
            return re.test(String(ccard));
        }
    </script>
</section>
{% endblock %}

app_sec/templates/index.html
{% extends "base.html" %}
{% block title %}eDeti Shop{% endblock %}
{% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/products.css') }}">
{% endblock %}
{% block body %}
<section class="container mt-5">
    <div class="text-center mb-5">
        <a href="{{ url_for('views.products') }}" class="btn btn-primary btn-lg">Our Products</a>
    </div>
</section>
{% endblock %}
{% block footer %}
<script type="text/javascript" src="{{ url_for('static', filename='javascript/index.js') }}"></script>
{% endblock %}

app_sec/templates/products.html
{% extends "base.html" %}
{% block title %}eDeti Shop{% endblock %}
{% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/products.css') }}">
{% endblock %}
{% block body %}
<div class="container">
    <h1 class="text-center mb-5">Products</h1>
    <div class="row">
        {% for product in lista %}
        <div class="col-md-4 mb-4">
            <div class="card h-100">
                <img src="{{ url_for('static', filename='images/' + product[5]) }}" class="card-img-top" alt="{{ product[3] }}">
                <div class="card-body d-flex flex-column">
                    <h5 class="card-title">{{ product[4] }}</h5>
                    <p class="card-text">{{ product[3] }}</p>
                    <div class="d-flex justify-content-between align-items-center mt-auto">
                        <span class="text-muted">{{ product[6] }}€</span>
                        <span>
                            {% if product[1] | int > 0 %}
                            <span class="badge bg-success">In Stock</span>
                            {% else %}
                            <span class="badge bg-danger">Out of Stock</span>
                            {% endif %}
                        </span>
                    </div>
                    <div class="mt-3 d-flex">
                        <form action="/product" method="POST" class="flex-fill me-2">
                            <input type="hidden" name="csrf_token" value="{{csrf_token()}}">
                            <input type="hidden" name="product_id" value="{{ product[0] }}">
                            <button type="submit" class="btn btn-secondary w-100">See Details</button>
                        </form>
                        
                        <form action="/add_cart" method="POST" class="flex-fill">
                            <input type="hidden" name="csrf_token" value="{{csrf_token()}}">
                            <input type="hidden" name="product_id" value="{{ product[0] }}">
                            <input type="number" name="quantity" value="1" 
                                   min="1" 
                                   max="{{ product[1] | int }}" 
                                   class="form-control" 
                                   required>
                            <button type="submit" class="btn btn-primary w-100">Add to Cart</button>
                        </form>
                    </div>
                    
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

app_sec/templates/profile.html
{% extends "base.html" %}
{% block title %}Profile - eDeti Shop{% endblock %}
{% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/profile.css') }}">
<meta http-equiv="Content-Security-Policy" content="default-src 'self'; img-src 'self' data:; script-src 'self' 'sha256-abc...'; style-src 'self' 'sha256-def...';">
{% endblock %}
{% block beforenav %}
<div class="d-flex flex-column" style="min-height: 100vh;">
{% endblock %}
{% block body %}
<div class="container profile-container">
    <div class="row">
        <div class="col-md-4">
            <div class="profile-sidebar">
                <div class="profile-image">
                    <img alt="Profile Image" src="{{ url_for('static', filename='uploads/' + (avatar if avatar else '../images/default.png')) }}" class="img-fluid">
                    <div class="profile-username mt-2">{{ username }}</div>
                    <div class="profile-email text-muted">{{ email }}</div>
                </div>
                <div class="profile-actions mt-4">
                    <a href="/logout" class="btn btn-secondary w-100">Logout</a>
                    {% if type == '0' %}
                    <a href="/add_product" class="btn btn-success w-100 mt-2">Add Product</a>
                    {% endif %}
                    
                    <form action="{{ url_for('auth.delete_account') }}" method="POST" onsubmit="return confirm('Are you sure you want to delete your account? This action cannot be undone.');">
                        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                        <button type="submit" class="btn btn-danger w-100 mt-2">Delete Account</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-md-8">
            <div class="settings">
                <h2 class="fw-bold mb-3">Change Password</h2>
                <p class="mb-4">Please enter your current password and new password!</p>
                <form action="/profile" method="POST" id="password-change-form">
                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                    
                    <div class="mb-4">
                        <label for="old-password" class="form-label">Current Password</label>
                        <input type="password" id="old-password" name="old-password" class="form-control form-control-lg" placeholder="Current Password" required>

                        {% if errors and errors.get('old-password') %}
                        <div class="text-danger mt-2">{{ errors['old-password'] }}</div>
                        {% endif %}
                    </div>
                    <div class="mb-4">
                        <label for="new-password" class="form-label">New Password</label>
                        <input type="password" id="new-password" name="new-password" class="form-control form-control-lg" placeholder="New Password" required>

                        {% if errors and errors.get('new-password') %}
                        <div class="text-danger mt-2">{{ errors['new-password'] }}</div>
                        {% endif %}

                        {% if errors and errors.get('breached') %}
                        <div class="text-danger mt-2">{{ errors['breached'] }}</div>
                        {% endif %}

                        {% if errors and errors.get('length') %}
                        <div class="text-danger mt-2">{{ errors['length'] }}</div>
                        {% endif %}
                    </div>
                    <div class="mb-4">
                        <label for="confirm-password" class="form-label">Confirm Password</label>
                        <input type="password" id="confirm-password" name="confirm-password" class="form-control form-control-lg" placeholder="Confirm Password" required>
                        {% if errors and errors.get('new-password') %}
                        <div class="text-danger mt-2">{{ errors['new-password'] }}</div>
                        {% endif %}
                    </div>
                    <div class="text-center">
                        <button class="btn btn-primary" type="submit" id="change-password">Change Password</button>
                    </div>
                </form>
                
                <h2 class="fw-bold mt-5 mb-3">Change Avatar</h2>
                <p class="mb-4">Upload a new avatar to update your profile picture.</p>
                <form action="/change_avatar" method="POST" enctype="multipart/form-data">
                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                
                    <div class="mb-4">
                        <label for="avatar" class="form-label">Select New Avatar (Optional)</label>
                        <input type="file" id="avatar" name="avatar" class="form-control form-control-lg" accept="image/*">
                        {% if errors and errors.get('avatar') %}
                        <div class="text-danger mt-2">{{ errors['avatar'] }}</div>
                        {% endif %}
                    </div>
                    <div class="text-center">
                        <button class="btn btn-primary" type="submit" id="change-avatar">Change Avatar</button>
                    </div>
                </form>
                
            </div>
        </div>
    </div>
</div>
<script src="{{ url_for('static', filename='javascript/profile.js') }}"></script>
{% endblock %}