app/views.py
from flask import Blueprint, render_template, redirect, url_for, request, session, flash
from .auth import session
from .database import *
from werkzeug.exceptions import BadRequest


views = Blueprint('views', __name__)

def validate_integer(value, field_name, min_value=None, max_value=None):
    try:
        value = int(value)
        if min_value is not None and value < min_value:
            raise ValueError(f"{field_name} must be at least {min_value}.")
        if max_value is not None and value > max_value:
            raise ValueError(f"{field_name} must be at most {max_value}.")
        return value
    except ValueError as e:
        raise BadRequest(str(e))

@views.route('/', methods=['GET', 'POST'])
def home():
    if 'user' in session:
        username = session['user']['username']
        return render_template('index.html', username=username)
    else:
        return redirect(url_for('auth.login'))

@views.route('/product', methods=['GET', 'POST'])
def product_detail():
    if request.method == 'GET':
        product_id = request.args.get('value')
        if not product_id or not product_id.isdigit():
            flash('A valid Product ID is required.', 'error')
            return redirect(url_for('home'))

        product_id = int(product_id)
        product = get_product_by_id(product_id)
        reviews = get_reviews(product_id)

        if not product:
            flash('Product not found.', 'error')
            return redirect(url_for('home'))

        return render_template('product.html', product=product, reviews=reviews)

    elif request.method == 'POST':
        product_id = request.form.get('product_id')
        if not product_id or not product_id.isdigit():
            flash('A valid Product ID is required.', 'error')
            return redirect(url_for('views.products'))

        product_id = int(product_id)
        product = get_product_by_id(product_id)
        reviews = get_reviews(product_id)

        if 'ratings' in request.form and 'p-review' in request.form:
            email = session.get('user', {}).get('email')
            if not email:
                flash('User must be logged in to add a review.', 'error')
                return redirect(url_for('login'))

            ratings = request.form.get('ratings')
            p_review = request.form.get('p-review')
            if not ratings or not ratings.isdigit():
                flash('A valid rating is required.', 'error')
            elif not p_review or not p_review.strip():
                flash('Review text cannot be empty.', 'error')
            else:
                try:
                    ratings = int(ratings)
                    if ratings < 1 or ratings > 5:
                        flash('Ratings must be between 1 and 5.', 'error')
                    else:
                        add_review(email, ratings, p_review.strip(), product_id)
                        flash('Review added successfully!', 'success')
                except ValueError:
                    flash('Invalid rating value.', 'error')
            reviews = get_reviews(product_id)

        return render_template('product.html', product=product, reviews=reviews)


@views.route('/about', methods=['GET', 'POST'])
def about():
    if request.method == 'POST':
        email = session['user']['email']
        return render_template('about.html', session_user=email)
    else:
        if 'user' in session:
            email = session['user']['email']
            return render_template('about.html', session_user=email)
        else:
            return redirect(url_for('auth.login'))

@views.route('/cart', methods=['GET'])
def cart():
    if 'user' in session:
        user = session['user']['username']
        return render_template('cart.html', user=user, cart=get_cart(user))
    else:
        return redirect(url_for('auth.login'))

@views.route('/checkout', methods=['GET'])
def checkout():
    if 'user' in session:
        return render_template('checkout.html', user=session['user']["username"])
    else:
        return redirect(url_for('auth.login'))

@views.route("/products", methods=['GET', 'POST'])
def products():
    if request.method == 'POST':
        query = request.form['query'].upper().split(" ")
        lista_produtos = get_specific_products(query)
        return render_template('products.html', lista=lista_produtos, user=session['user']["username"])
    else:
        if 'user' in session:
            return render_template('products.html', lista=get_products(), user=session['user']["username"])
        else:
            return redirect(url_for('auth.login'))

@views.route("/add_cart", methods=['POST'])
def add_cart():
    if 'user' in session:
        user = session['user']['username']
        
        try:
            product_id = validate_integer(request.form.get('product_id'), 'Product ID', min_value=1)
            quantity = validate_integer(request.form.get('quantity'), 'Quantity', min_value=1)
        except BadRequest as e:
            flash(str(e))
            return redirect(request.referrer)
        product = get_product(product_id)

        if product and quantity:
            try:
                add_to_cart(quantity, product[6], product[4], user)
                flash('Product added to cart successfully!', 'success')
            except Exception as e:
                flash(f'Error adding product to cart: {e}', 'danger')
        else:
            flash('Invalid input data.', 'danger')
        return redirect(url_for('views.cart'))
    return redirect(url_for('auth.login'))

@views.route("/remove_item", methods=['POST'])
def remove_item():
    if 'user' in session:
        user = session['user']['username']
        product_id = request.form.get('product_id')
        if product_id:
            remove_from_cart(user, product_id)
            product = get_product_by_id(product_id)
            if product:
                add_quantity(product[4], request.form.get('quantity', 1))
            flash('Item removed from cart successfully!', 'success')
        else:
            flash('Error: Product ID not found.', 'danger')
        return redirect(url_for('views.cart'))
    else:
        return redirect(url_for('auth.login'))

@views.route("/pay", methods=['POST'])
def pay():
    if 'user' in session:
        user = session['user']['username']
        pay_cart(user)
        return redirect(url_for('views.home'))
    return redirect(url_for('auth.login'))

app/templates/about.html
{% extends "base.html" %}
{% block title %}eDeti Shop{% endblock %}
{% block head %}
<link rel="stylesheet" href="{{url_for('static', filename='css/about.css')}}">
{% endblock %}
<div class="d-flex flex-column" style="min-height: 990px;"></div>
{% block body %}

<section class="about">
  <div class="about-section">
      <h1>About Us Page</h1>
      <p>This is the about us page of the project of Segurança Informática e nas Organizações</p>
      <p>This project was done by:</p>
      <p>Francisco Gonçalves Nmec: 1085381</p>
    </div>  
    
  <div class="about-description">
    <h3>Project description</h3>
    <p>The assignment focuses on vulnerabilities in software projects, their exploration, and prevention. 
      We were required to develop a small online shop application selling memorabilia for the Department of Electronics, 
      Telecommunications, and Informatics (DETI) at the University of Aveiro. The online shop features items like mugs, cups, 
      t-shirts, hoodies, and similar memorabilia.</p>
      <p>In this project we implemented some CWE that were requested such as:</p>
      <p>CWE-79 (Cross-Site Scripting) <br>CWE-89 (SQL Injection)</p>
      <p>We also implemented others vulnerabilities:</p>      
      <p>Cwe-20: Improper Input Validation</p>
      <p>CWE-22 Improper Limitation of a Pathname to a Restricted Directory ('Path Traversal')</p>
      <p>CWE-521: Weak Password Requirements</p>      
      <p>CWE-522 - Insufficiently Protected Credentials</p>
      <p>CWE-601: URL Redirection to Untrusted Site ('Open Redirect')</p>
      <p>CWE-798 Use of Hard-coded Credentials</p>
  </div>
</section>

{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{url_for('static', filename='css/bootstrap.css')}}">
    <!-- Font Awesome -->
    <link
    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
    rel="stylesheet"
    />
    <link href="https://fonts.cdnfonts.com/css/amazon-ember" rel="stylesheet">
    <style>
      @import url('https://fonts.cdnfonts.com/css/amazon-ember');
    </style>
    <!-- Handle JQuery -->
    <script type="text/javascript" src="https://code.jquery.com/jquery-1.7.1.min.js"></script>
    <!-- Google Fonts -->
    <!-- <link
    href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
    rel="stylesheet"
    /> -->
    <style>
      @import url('https://fonts.googleapis.com/css2?family=Open+Sans:wght@500&display=swap');
    </style>
    <!-- Inter font -->
    <link href='https://fonts.googleapis.com/css?family=Inter' rel='stylesheet'>
    <!-- Bootstrap 5 -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">    {% block head %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>
    <!-- Custom CSS -->
    <link rel="stylesheet" href=" {{ url_for('static', filename='css/base.css') }}">
    <link rel="stylesheet" href=" {{ url_for('static', filename='css/style.css') }}">
</head>
  {% block beforenav %}{% endblock %}
    <header>
      <div class="navbar">
          <div class="logo"><a href="/">eDeti shop</a></div>
          <ul class="links">
              <li><a href="/">Home</a></li>
              <li><a href="/about">About Us</a></li>
          </ul>
          <div class="col-r">
            <a href="/cart" class="shop-cart"><i class="fa-solid fa-shopping-cart"></i></a>
            <a href="/profile" class="shop-cart"><i class="fa-solid fa-user"></i></a>
          </div>
          <div class="toggle_btn">
              <i class="fa-solid fa-bars"></i>
          </div>

          <div class="dropdown_menu">
              <li><a href="/">Home</a></li>
              <li><a href="/about">About Us</a></li>
              <li><a href="/products" class="action_btn">Shop Now</a></li>
              <li><a href="/cart" class="shop-cart"><i class="fa-solid fa-shopping-cart"></i></a></li>
          </div>
      </div>

      <script>
          const toggleBtn = document.querySelector('.toggle_btn')
          const toggleBtnIcon = document.querySelector('.toggle_btn i')
          const dropDownMenu = document.querySelector('.dropdown_menu')

          toggleBtn.onclick = function () {
              dropDownMenu.classList.toggle('open')
          }
      </script>
  </header>
  {% block body %}
  {% endblock %}


  <footer class="footer">
    <div class="container">
      <p>© 2023 DETI, Universidade de Aveiro</p>
    </div>
  </footer>
</html>

app/templates/cart.html
{% extends "base.html" %}
{% block title %}eDeti Shop{% endblock %}
{% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/cart.css') }}">
{% endblock %}
{% block body %}
<div class="container mt-5">
    <div class="cart-container">
        <h1 class="mb-4">Your Shopping Cart</h1>
        <table class="table">
            <thead>
                <tr>
                    <th>Item Name</th>
                    <th>Quantity</th>
                    <th>Price</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% for item in cart %}
                <tr>
                    <td>{{ item[3] | e }}</td>  <!-- Escapes output to prevent XSS -->
                    <td>{{ item[1] | e }}</td>
                    <td>{{ item[2] | e }}</td>
                    <td>
                        <form method="POST" action="{{ url_for('views.remove_item') }}">
                            <input type="hidden" name="csrf_token" value="{{csrf_token()}}">
                            <button class="btn btn-danger action-button" type="submit">Remove</button>
                            <input type="hidden" name="product_id" value="{{ item[0] | e }}">  <!-- Escape to prevent potential XSS -->
                        </form>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <a class="action_btn" href="/checkout">Checkout</a>
    </div>
</div>
{% endblock %}

app/templates/checkout.html
{% extends "base.html" %}
{% block title %}eDeti Shop{% endblock %}
{% block head %}
<link rel="stylesheet" href="{{url_for('static', filename='css/checkout.css')}}">
{% endblock %}
{% block body %}
<section class="c-wrapper">
    <div class="c-left">
        <h1>Checkout</h1>
        <div class="shadow-line"></div>
        <div class="l-box">
            <h2>Your basic information</h2>
            <ul class="l-inputs">
                <li>
                    <label for="fname">First name*</label><br>
                    <input type="text" id="fname" name="fname"><br>
                </li>
                <li>
                    <label for="lname">Last name*</label><br>
                    <input type="text" id="lname" name="lname"><br>
                </li>
                <li>
                    <label for="email">Email*</label><br>
                    <input type="email" id="email" name="email">
                </li>
            </ul>
        </div>
        <div class="shadow-line"></div>
        <div class="l-box">
            <h2>Your Payment Information</h2>
            <!--Payement-->
            <ul class="l-pay">
                <li>
                    <label for="ccard">Credit Card*</label><br>
                    <input type="number" id="ccard" name="ccard" placeholder="XXXX XXXX XXXX XXXX"><br>
                </li>
                <li>
                    <label for="exp">Expiry date*</label><br>
                    <input type="month" id="exp" name="exp" placeholder="mm/yy"><br>
                </li>
                <li>
                    <label for="cvcv">CVC/CVV*</label><br>
                    <input type="number" id="cvcv" name="cvcv" placeholder="XXX">
                </li>
            </ul>
            <form method="POST" action="pay">
                <input type="hidden" name="csrf_token" value="{{csrf_token()}}">
                <button class="action_btn">Proceed</button>
            </form>
        </div>
    </div>
</section>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}
{% block title %}eDeti Shop{% endblock %}
{% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/products.css') }}">
{% endblock %}
{% block body %}
<section class="container mt-5">
    <div class="text-center mb-5">
        <a href="{{ url_for('views.products') }}" class="btn btn-primary btn-lg">Our Products</a>
    </div>
</section>
{% endblock %}
{% block footer %}
<script type="text/javascript" src="{{ url_for('static', filename='javascript/index.js') }}"></script>
{% endblock %}

app/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.2.0/mdb.min.css">
    <link rel="icon" type="image/x-icon" href="{{url_for('static',filename='images/logo_title.png')}}">
    <link rel="stylesheet" href="{{url_for('static', filename='css/auth.css')}}">
</head>
<body>
    <section class="gradient-custom">
        <div class="login-main-container">
            <div class="login-container">
                <div class="login-card">
                    <div class="login-card-body text-center">
                        <div class="mb-md-5 mt-md-4 pb-5">
                            <form method="POST" action="{{ url_for('auth.login') }}">
                                <input type="hidden" name="csrf_token" value="{{csrf_token()}}">
                                <h2 class="fw-bold mb-2 text-uppercase">login</h2>
                                <p class="alpha-60 mb-5">Insira o seu email e password!</p>
                                <div class="form-outline form-white mb-4">
                                    <input id="email" name="email" {% if incorrect_email is defined %}value="{{email}}" {% endif %} class="form-control form-control-lg" placeholder="example@hotmail.com"/>
                                    <label class="form-label" for="email">Email</label>
                                    <span id="email-error">{% if incorrect_email is defined %}Você ainda não está registado.{% endif %}</span>
                                </div>
                                <div class="form-outline form-white mb-4">
                                    <input type="password" id="password" name="password" class="form-control form-control-lg" placeholder=" "/>
                                    <label class="form-label" for="typePasswordX">Password</label>
                                    <span id="password1-error">{% if incorrect_password is defined %}Password incorreta.{% endif %}</span>
                                    <div class="form-check mt-3 text-left">
                                        <input class="form-check-input" type="checkbox" id="showPassword" onclick="togglePassword()">
                                        <label class="form-check-label" for="showPassword">Mostrar Password</label>
                                    </div>
                                </div>
                                <p class="small mb-5 pb-lg-2"><a class="alpha-60" href="#!">Esqueceu-se da password?</a></p>
                                <button class="btn login-btn btn-lg px-5" type="submit" id="login">Login</button>
                            </form>
                        </div>
                        <div>
                            <p class="mb-0">Ainda não tem conta? <a href="/sign-up" class="alpha-60 fw-bold">Sign Up</a></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <script src="{{url_for('static', filename='javascript/login.js')}}"></script>
</body>
</html>

app/templates/product.html
{% extends "base.html" %}
{% block title %}eDeti Shop{% endblock %}
{% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/product.css') }}">
{% endblock %}
<div class="d-flex flex-column" style="min-height: 990px;"></div>
{% block body %}
<section class="container product my-5 pt-5">
    <div class="row mt-5">
        {% if product and product|length > 5 %}
        <div class="col-lg-5 col-md-12 col-12">
            <img src="{{ url_for('static', filename='images/' + product[5]) }}" class="card-img-top" alt="{{ product[3] }}">
        </div>

        <div class="col-lg-6 mx-5 mt-2 col-md-12 col-12">
            <h3 class="py-2">{{ product[4] }}</h3>
            <h2>{{ product[6] }}€</h2>
            <form method="POST" action="/add_cart">
                <input type="hidden" name="csrf_token" value="{{csrf_token()}}">
                <input type="number" value="1" min="1" max="{{ product[4] }}" name="quantity">
                <input type="hidden" name="product_id" value="{{ product[0] }}">
                <input type="hidden" name="product_name" value="{{ product[3] }}">
                <button class="action_btn">Add to cart</button>
            </form>
            <h4 class="mt-3 mb-3">Product Details</h4>
            <span>{{ product[3] }}</span>
        </div>
        {% else %}
        <div class="col-12">
            <p>Product not found or data is incomplete.</p>
        </div>
        {% endif %}
        <section class="wrapper">
            <div class="review-container">
                <h1>Post a Review</h1>
                <form class="post-review" method="POST" action="/product">
                    <input type="hidden" name="csrf_token" value="{{csrf_token()}}">
                    <input type="hidden" name="product_id" value="{{ product[0] }}">
                    <label for="ratings">Product Evaluation*</label>
                    <select id="ratings" name="ratings">
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                        <option value="5">5</option>
                    </select>
                    <label for="p-review">Write your Review*</label>
                    <textarea id="p-review" name="p-review"></textarea>
                    <button id="review-button" class="action_btn">Send Review</button>
                </form>
                <div class="reviews">
                    {% for review in reviews %}
                    <div class="review">
                        <ul class="userID">
                            <li><img src="{{ url_for('static', filename='images/default.png') }}" alt="Avatar" /></li>
                            <li>{{ review[1] }}</li> 
                        </ul>
                        <ul>
                            <li>Rating: {{ review[2] }}</li>
                            <li>24/07/23</li>
                        </ul>
                        <p class="rtext">{{ review[3] }}</p>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </section>
    </div>
</section>
{% endblock %}

app/templates/products.html
{% extends "base.html" %}
{% block title %}eDeti Shop{% endblock %}
{% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/products.css') }}">
{% endblock %}
{% block body %}
<div class="container">
    <h1 class="text-center mb-5">Products</h1>
    <div class="row">
        {% for product in lista %}
        <div class="col-md-4 mb-4">
            <div class="card h-100">
                <img src="{{ url_for('static', filename='images/' + product[5]) }}" class="card-img-top" alt="{{ product[3] }}">
                <div class="card-body d-flex flex-column">
                    <h5 class="card-title">{{ product[4] }}</h5>
                    <p class="card-text">{{ product[3] }}</p>
                    <div class="d-flex justify-content-between align-items-center mt-auto">
                        <span class="text-muted">{{ product[6] }}€</span>
                        <span>
                            {% if product[1] | int > 0 %}
                            <span class="badge bg-success">In Stock</span>
                            {% else %}
                            <span class="badge bg-danger">Out of Stock</span>
                            {% endif %}
                        </span>
                    </div>
                    <div class="mt-3 d-flex">
                        <form action="/product" method="POST" class="flex-fill me-2">
                            <input type="hidden" name="csrf_token" value="{{csrf_token()}}">
                            <input type="hidden" name="product_id" value="{{ product[0] }}">
                            <button type="submit" class="btn btn-secondary w-100">See Details</button>
                        </form>
                        
                        <form action="/add_cart" method="POST" class="flex-fill">
                            <input type="hidden" name="csrf_token" value="{{csrf_token()}}">
                            <input type="hidden" name="product_id" value="{{ product[0] }}">
                            <input type="number" name="quantity" value="1" 
                                   min="1" 
                                   max="{{ product[1] | int }}" 
                                   class="form-control" 
                                   required>
                            <button type="submit" class="btn btn-primary w-100">Add to Cart</button>
                        </form>
                    </div>
                    
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

app/templates/profile.html
{% extends "base.html" %}
{% block title %}Profile - eDeti Shop{% endblock %}
{% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/profile.css') }}">
<meta http-equiv="Content-Security-Policy" content="default-src 'self'; img-src 'self' data:; script-src 'self' 'sha256-abc...'; style-src 'self' 'sha256-def...';">
{% endblock %}
{% block beforenav %}
<div class="d-flex flex-column" style="min-height: 100vh;">
{% endblock %}
{% block body %}
<div class="container profile-container">
    <div class="row">
        <div class="col-md-4">
            <div class="profile-sidebar">
                <div class="profile-image">
                    <!-- Display user avatar -->
                    <img alt="Profile Image" src="{{ url_for('static', filename='uploads/' + (avatar if avatar else '../images/default.png')) }}" class="img-fluid">
                    <div class="profile-username mt-2">{{ username }}</div>
                    <div class="profile-email text-muted">{{ email }}</div>
                </div>
                <div class="profile-actions mt-4">
                    <a href="/logout" class="btn btn-secondary w-100">Logout</a>
                    {% if type == '0' %}
                    <a href="/add_product" class="btn btn-success w-100 mt-2">Add Product</a>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="col-md-8">
            <div class="settings">
                <!-- Form for changing password -->
                <h2 class="fw-bold mb-3">Change Password</h2>
                <p class="mb-4">Please enter your current password and new password!</p>
                <form action="/profile" method="POST" id="password-change-form">
                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                    
                    <div class="mb-4">
                        <label for="old-password" class="form-label">Current Password</label>
                        <input type="password" id="old-password" name="old-password" class="form-control form-control-lg" placeholder="Current Password" required>
                    </div>
                    <div class="mb-4">
                        <label for="new-password" class="form-label">New Password</label>
                        <input type="password" id="new-password" name="new-password" class="form-control form-control-lg" placeholder="New Password" required>
                    </div>
                    <div class="mb-4">
                        <label for="confirm-password" class="form-label">Confirm Password</label>
                        <input type="password" id="confirm-password" name="confirm-password" class="form-control form-control-lg" placeholder="Confirm Password" required>
                    </div>
                    <div class="text-center">
                        <button class="btn btn-primary" type="submit" id="change-password">Change Password</button>
                    </div>
                </form>
                
                <!-- Form for changing avatar -->
                <h2 class="fw-bold mt-5 mb-3">Change Avatar</h2>
                <p class="mb-4">Upload a new avatar to update your profile picture.</p>
                <form action="/change_avatar" method="POST" enctype="multipart/form-data">
                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                
                    <!-- Avatar Upload -->
                    <div class="mb-4">
                        <label for="avatar" class="form-label">Select New Avatar (Optional)</label>
                        <input type="file" id="avatar" name="avatar" class="form-control form-control-lg" accept="image/*">
                    </div>
                    <div class="text-center">
                        <button class="btn btn-primary" type="submit" id="change-avatar">Change Avatar</button>
                    </div>
                </form>
                
            </div>
        </div>
    </div>
</div>
<script src="{{ url_for('static', filename='javascript/profile.js') }}"></script>
{% endblock %}